apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://${k8s_host}:443
  name: gke-cluster
contexts:
- context:
    cluster: gke-cluster
    user: gke-kube
  name: gke-system
current-context: gke-system
preferences: {}
users:
- name: gke-kube
  user:
    username: ${k8s_username}
    password: ${k8s_password}
